# Generated by Django 5.1.1 on 2024-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_updater_name', models.CharField(max_length=100)),
                ('crime_updater_position', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('crime_type', models.CharField(choices=[('THEFT', 'Theft'), ('ASSAULT', 'Assault'), ('MURDER', 'Murder'), ('ROBBERY', 'Robbery')], max_length=20)),
            ],
        ),
    ]
