# Generated by Django 5.1.1 on 2024-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='crime_type',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='crime_updater_name',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='crime_updater_position',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='place',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='time',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='minutes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
