# Generated by Django 5.1.1 on 2024-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_crimereport_crime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='crime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
